(:name           "EVidenceModeler")
(:repo           "taffish-org/EVidenceModeler")
(:author         "KaiyuanHan")
(:version        "2.1.0")
(:intro          "The EVidenceModeler (aka EVM) software combines ab intio gene predictions and protein and transcript alignments into weighted consensus gene structures.")
(:dependencies)
(:functions      "EVidenceModeler")
